CC = gcc
CFLAGS = -DQUIEN_ALL -Wall -g
#CFLAGS = -DQUIEN_UTENT -Wall -g
#CFLAGS = -Wall -g

OBJETOS = quien1.o 

PROGS = quien1

all: $(PROGS)

Quien1: quien1.o 
	$(CC) -g -o $@ $<

$(OBJETOS): quien.h

%.o : %.c 
	gcc -c $(CFLAGS) $<

clean :
	-rm $(OBJETOS) $(PROGS) 	
